name: my_stand_clock
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  analog_clock: ^0.1.1
  animated_analog_clock: ^0.2.2
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  connectivity_plus: ^6.1.4
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  firebase_core: ^3.10.0
  firebase_crashlytics: ^4.2.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  geolocator: ^13.0.3
  google_fonts: ^4.0.3
  google_nav_bar: ^5.0.6
  http: ^1.6.0
  intl: ^0.18.1
  permission_handler: ^10.4.0
  shared_preferences: ^2.1.1
  url_launcher: ^6.1.0
  wakelock_plus: ^1.4.0

dev_dependencies:
  bloc_test: ^9.1.0

  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env

dependency_overrides:
  permission_handler_android: ^13.0.1
  permission_handler_platform_interface: ^4.3.0
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
